[package]
name = "seedsimrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
inline_colorization = "0.1.6"
rand = "0.8.5"
vector2d = "2.2.0"
